In [2]:
from pathlib import Path
import pandas as pd

project_root = Path(
    r"C:\Users\lenovo\OneDrive\Desktop\job_postings_project"
)

path = (
    project_root
    / "artifacts"
    / "salary_feature_store"
    / "latest"
    / "salary_modeling_dataset.parquet"
)

print(path)
print("Exists:", path.exists())

salary_df = pd.read_parquet(path)

print("Shape:", salary_df.shape)

display(salary_df.head())

C:\Users\lenovo\OneDrive\Desktop\job_postings_project\artifacts\salary_feature_store\latest\salary_modeling_dataset.parquet
Exists: True
Shape: (48122, 23)

,target_annual_salary,target_log_salary,salary_target_source,title,formatted_experience_level,formatted_work_type,company_state,company_country,company_size,company_employee_count,...,skill_list,skill_count,log_company_employee_count,log_company_follower_count,posting_group_id,company_name,location,original_listed_time,listed_time,dataset_version
0,63000.0,11.050906,MEDIAN_SALARY,Hearing Care Provider,entry level,full-time,new jersey,us,5.0,1171,...,OTHER,1,7.066467,9.342946,54d0b92d78862631585114583adb1e53870a1a098fbfd9...,HearingLife,"Little River, SC",2023-11-04 09:26:40,2023-11-04 09:26:40,Version_9
1,46321.6,10.743385,MEDIAN_SALARY,Cook,entry level,full-time,california,us,4.0,36,...,MANAGEMENT|MANUFACTURING,2,3.610918,5.723585,13f45183fdcc7fbdb775c2754b43e1b34b0df8c52d238d...,Episcopal Communities & Services,"Aliso Viejo, CA",2023-11-04 06:40:00,2023-11-04 06:40:00,Version_9
2,240895.0,12.392121,RANGE_MIDPOINT,Principal Cloud Security Architect (Remote),mid-senior level,full-time,california,us,5.0,1260,...,INFORMATION_TECHNOLOGY,1,7.139660,10.852284,8424f308a52492aaf9997a3ccd398d05e63cba90d48d61...,"iHerb, LLC",United States,2023-11-03 00:06:40,2023-11-04 09:26:40,Version_9
3,40144.0,10.600253,MEDIAN_SALARY,Dishwasher,entry level,full-time,california,us,4.0,36,...,MANAGEMENT|MANUFACTURING,2,3.610918,5.723585,9091de0ea33180f1826799badd27d66edc2d09ee23bc32...,Episcopal Communities & Services,"Aliso Viejo, CA",2023-11-04 06:40:00,2023-11-04 06:40:00,Version_9
4,61000.0,11.018646,RANGE_MIDPOINT,Insights Analyst - Auto Industry,entry level,full-time,mi,us,4.0,894,...,ANALYST|INFORMATION_TECHNOLOGY|RESEARCH,3,6.796824,11.185046,537fad955fcc4af8688335fa0ba02a4607e7bc1f305fb6...,Escalent,United States,2023-11-02 21:20:00,2023-11-04 09:26:40,Version_9

In [4]:
print("=" * 80)
print("SALARY MODELING DATASET — BASIC INFORMATION")
print("=" * 80)

print("Shape:", salary_df.shape)

print("\nColumns:")
for i, col in enumerate(salary_df.columns, 1):
    print(f"{i:02d}. {col}")

print("\nData types:")
print(salary_df.dtypes)

================================================================================
SALARY MODELING DATASET — BASIC INFORMATION
================================================================================
Shape: (48122, 23)

Columns:
01. target_annual_salary
02. target_log_salary
03. salary_target_source
04. title
05. formatted_experience_level
06. formatted_work_type
07. company_state
08. company_country
09. company_size
10. company_employee_count
11. company_follower_count
12. top_industry
13. top_skill
14. skill_list
15. skill_count
16. log_company_employee_count
17. log_company_follower_count
18. posting_group_id
19. company_name
20. location
21. original_listed_time
22. listed_time
23. dataset_version

Data types:
target_annual_salary                 float64
target_log_salary                    float64
salary_target_source          string[python]
title                                 object
formatted_experience_level            object
formatted_work_type                   object
company_state                         object
company_country                       object
company_size                          object
company_employee_count                 int64
company_follower_count                 int64
top_industry                          object
top_skill                             object
skill_list                            object
skill_count                            int64
log_company_employee_count           float64
log_company_follower_count           float64
posting_group_id                      object
company_name                          object
location                              object
original_listed_time                  object
listed_time                           object
dataset_version                       object
dtype: object

In [5]:
print("=" * 80)
print("SALARY MODELING DATASET — BASIC INFORMATION")
print("=" * 80)

print("Shape:", salary_df.shape)

print("\nColumns:")
for i, col in enumerate(salary_df.columns, 1):
    print(f"{i:02d}. {col}")

print("\nData types:")
print(salary_df.dtypes)

================================================================================
SALARY MODELING DATASET — BASIC INFORMATION
================================================================================
Shape: (48122, 23)

Columns:
01. target_annual_salary
02. target_log_salary
03. salary_target_source
04. title
05. formatted_experience_level
06. formatted_work_type
07. company_state
08. company_country
09. company_size
10. company_employee_count
11. company_follower_count
12. top_industry
13. top_skill
14. skill_list
15. skill_count
16. log_company_employee_count
17. log_company_follower_count
18. posting_group_id
19. company_name
20. location
21. original_listed_time
22. listed_time
23. dataset_version

Data types:
target_annual_salary                 float64
target_log_salary                    float64
salary_target_source          string[python]
title                                 object
formatted_experience_level            object
formatted_work_type                   object
company_state                         object
company_country                       object
company_size                          object
company_employee_count                 int64
company_follower_count                 int64
top_industry                          object
top_skill                             object
skill_list                            object
skill_count                            int64
log_company_employee_count           float64
log_company_follower_count           float64
posting_group_id                      object
company_name                          object
location                              object
original_listed_time                  object
listed_time                           object
dataset_version                       object
dtype: object

In [6]:
categorical_features = [
    "formatted_experience_level",
    "formatted_work_type",
    "company_state",
    "company_country",
    "company_size",
    "top_industry",
    "top_skill",
]

for col in categorical_features:

    if col not in salary_df.columns:
        continue

    print("\n" + "=" * 70)
    print(col)
    print("=" * 70)

    print("Unique values:", salary_df[col].nunique(dropna=True))

    display(
        salary_df[col]
        .value_counts(dropna=False)
        .head(20)
    )

======================================================================
formatted_experience_level
======================================================================
Unique values: 7

formatted_experience_level
mid-senior level    17285
entry level         11995
unknown             10945
associate            5084
director             1824
executive             503
internship            486
Name: count, dtype: int64

======================================================================
formatted_work_type
======================================================================
Unique values: 7

formatted_work_type
full-time     39415
contract       4950
part-time      2801
temporary       495
internship      287
other           171
volunteer         3
Name: count, dtype: int64

======================================================================
company_state
======================================================================
Unique values: 382

company_state
ca            4649
california    4267
ny            3355
0             3251
texas         2018
new york      1537
illinois      1332
georgia       1052
tx             982
il             958
va             943
florida        933
wa             892
new jersey     848
ma             828
nj             807
fl             789
pa             738
virginia       717
ga             654
Name: count, dtype: int64

======================================================================
company_country
======================================================================
Unique values: 50

company_country
us    43814
gb     1523
0       894
ca      443
ch      198
de      184
fr      158
se      116
in      114
nl      107
ie       65
au       61
no       56
dk       53
jp       52
oo       48
cn       29
be       29
it       21
sg       19
Name: count, dtype: int64

======================================================================
company_size
======================================================================
Unique values: 8

company_size
7.0        14615
5.0         9093
2.0         5988
1.0         4215
3.0         4054
6.0         4027
4.0         3748
unknown     2382
Name: count, dtype: int64

======================================================================
top_industry
======================================================================
Unique values: 348

top_industry
hospitals and health care           4944
staffing and recruiting             3972
it services and it consulting       2750
financial services                  2224
retail                              2055
software development                1571
banking                             1315
accounting                          1126
construction                        1096
biotechnology research               937
government administration            875
manufacturing                        860
advertising services                 826
hospitality                          765
insurance                            736
higher education                     726
real estate                          707
business consulting and services     678
law practice                         667
non-profit organizations             660
Name: count, dtype: int64

======================================================================
top_skill
======================================================================
Unique values: 35

top_skill
management                6815
health care provider      4721
information technology    4602
engineering               4558
business development      4511
other                     3669
accounting/auditing       3111
administrative            2292
marketing                 1821
finance                   1607
analyst                   1422
legal                     1051
human resources           1010
customer service           944
consulting                 785
art/creative               690
education                  681
sales                      658
manufacturing              453
quality assurance          429
Name: count, dtype: int64

In [7]:
salary_df["target_annual_salary"].describe(
    percentiles=[
        0.01,
        0.05,
        0.10,
        0.25,
        0.50,
        0.75,
        0.90,
        0.95,
        0.99,
        0.995,
        0.999
    ]
)

count     48122.000000
mean      96533.480490
std       60434.542978
min       10000.000000
1%        27040.000000
5%        34538.400000
10%       39520.000000
25%       52408.200000
50%       82500.000000
75%      125000.000000
90%      168895.000000
95%      200000.000000
99%      290825.875000
99.5%    350000.000000
99.9%    561895.000000
max      998426.000000
Name: target_annual_salary, dtype: float64

In [8]:
target = salary_df["target_annual_salary"]

print("Minimum:", target.min())
print("Maximum:", target.max())
print("Mean:", target.mean())
print("Median:", target.median())

print("\n> $200K:", (target > 200_000).sum())
print("> $300K:", (target > 300_000).sum())
print("> $500K:", (target > 500_000).sum())
print("> $900K:", (target > 900_000).sum())
print("= $1M:", (target == 1_000_000).sum())

Minimum: 10000.0
Maximum: 998426.0
Mean: 96533.48049042017
Median: 82500.0

> $200K: 2327
> $300K: 401
> $500K: 71
> $900K: 7
= $1M: 0

In [9]:
display(
    salary_df
    .sort_values(
        "target_annual_salary",
        ascending=False
    )[
        [
            "title",
            "target_annual_salary",
            "salary_target_source",
            "formatted_experience_level",
            "top_industry",
            "top_skill",
        ]
    ]
    .head(30)
)

,title,target_annual_salary,salary_target_source,formatted_experience_level,top_industry,top_skill
8975,Criminal Court Clerk,998426.0,MEDIAN_SALARY,entry level,government administration,legal
21246,Modernization Software Dev,960000.0,RANGE_MIDPOINT,associate,it services and it consulting,information technology
46006,Quantitative Researcher,950000.0,RANGE_MIDPOINT,mid-senior level,capital markets,engineering
39302,"Corporate, Litigation, Intellectual Property ,...",925000.0,RANGE_MIDPOINT,unknown,law practice,legal
14483,Partner (& Groups w/ Portable Business for Top...,925000.0,RANGE_MIDPOINT,unknown,law practice,legal
14444,Partner (& Groups w/ Portable Business for Top...,925000.0,RANGE_MIDPOINT,unknown,law practice,legal
14431,Partner (& Groups w/ Portable Business for Top...,925000.0,RANGE_MIDPOINT,unknown,law practice,legal
7042,Tech Lead Manager (L6-L8) | Disruptive FinTech,875000.0,RANGE_MIDPOINT,mid-senior level,financial services,engineering
45255,Head of Front Office Technology,875000.0,RANGE_MIDPOINT,unknown,capital markets,information technology
46197,Quantitative Researcher,825000.0,RANGE_MIDPOINT,mid-senior level,capital markets,engineering
6812,Fintech Startup | Tech Lead Manager - Software...,800000.0,RANGE_MIDPOINT,mid-senior level,financial services,engineering
7187,Head of Sales & Marketing (Healthcare),800000.0,MEDIAN_SALARY,unknown,hospitals and health care,business development
9859,"Distinguished Engineer, Trilogy (Remote) - $80...",800000.0,MEDIAN_SALARY,executive,it services and it consulting,art/creative
9811,"Chief Software Architect, Trilogy (Remote) - $...",800000.0,MEDIAN_SALARY,executive,it services and it consulting,business development
2195,Registered Nurse or Licensed Practical Nurse -...,785358.0,MEDIAN_SALARY,unknown,staffing and recruiting,health care provider
9644,"Director of Product, MyBSWHealth",750000.0,MEDIAN_SALARY,director,hospitals and health care,marketing
34029,Litigation Partner,750000.0,RANGE_MIDPOINT,director,law practice,legal
22696,Oral Surgeon - DDS/DMD,750000.0,MEDIAN_SALARY,mid-senior level,hospitals and health care,health care provider
34057,Labor & Employment Partner,750000.0,RANGE_MIDPOINT,director,law practice,legal
34092,Trust and Estates Partner,750000.0,RANGE_MIDPOINT,director,law practice,legal
34103,Intellectual Property Partner,750000.0,RANGE_MIDPOINT,director,law practice,legal
28542,Senior Sales Account Executive - Enterprise,750000.0,MEDIAN_SALARY,mid-senior level,software development,business development
9539,"Director of Product, MyBSWHealth",750000.0,MEDIAN_SALARY,director,hospitals and health care,marketing
45748,Python Developer,750000.0,RANGE_MIDPOINT,mid-senior level,capital markets,engineering
46598,Senior Software Engineer,750000.0,RANGE_MIDPOINT,mid-senior level,financial services,engineering
45693,Network Engineer,750000.0,RANGE_MIDPOINT,mid-senior level,capital markets,engineering
8747,Senior Project Manager,750000.0,MEDIAN_SALARY,mid-senior level,pharmaceutical manufacturing,information technology
40167,Oral Surgeon,700000.0,RANGE_MIDPOINT,mid-senior level,hospitals and health care,health care provider
40956,NEO4J- Senior Database administrator,700000.0,RANGE_MIDPOINT,unknown,it services and it consulting,information technology
23589,Orthopedic Surgeon,680000.0,MEDIAN_SALARY,mid-senior level,staffing and recruiting,health care provider

In [10]:
display(
    salary_df
    .sort_values(
        "target_annual_salary",
        ascending=False
    )[
        [
            "title",
            "target_annual_salary",
            "salary_target_source",
            "formatted_experience_level",
            "top_industry",
            "top_skill",
        ]
    ]
    .head(30)
)

,title,target_annual_salary,salary_target_source,formatted_experience_level,top_industry,top_skill
8975,Criminal Court Clerk,998426.0,MEDIAN_SALARY,entry level,government administration,legal
21246,Modernization Software Dev,960000.0,RANGE_MIDPOINT,associate,it services and it consulting,information technology
46006,Quantitative Researcher,950000.0,RANGE_MIDPOINT,mid-senior level,capital markets,engineering
39302,"Corporate, Litigation, Intellectual Property ,...",925000.0,RANGE_MIDPOINT,unknown,law practice,legal
14483,Partner (& Groups w/ Portable Business for Top...,925000.0,RANGE_MIDPOINT,unknown,law practice,legal
14444,Partner (& Groups w/ Portable Business for Top...,925000.0,RANGE_MIDPOINT,unknown,law practice,legal
14431,Partner (& Groups w/ Portable Business for Top...,925000.0,RANGE_MIDPOINT,unknown,law practice,legal
7042,Tech Lead Manager (L6-L8) | Disruptive FinTech,875000.0,RANGE_MIDPOINT,mid-senior level,financial services,engineering
45255,Head of Front Office Technology,875000.0,RANGE_MIDPOINT,unknown,capital markets,information technology
46197,Quantitative Researcher,825000.0,RANGE_MIDPOINT,mid-senior level,capital markets,engineering
6812,Fintech Startup | Tech Lead Manager - Software...,800000.0,RANGE_MIDPOINT,mid-senior level,financial services,engineering
7187,Head of Sales & Marketing (Healthcare),800000.0,MEDIAN_SALARY,unknown,hospitals and health care,business development
9859,"Distinguished Engineer, Trilogy (Remote) - $80...",800000.0,MEDIAN_SALARY,executive,it services and it consulting,art/creative
9811,"Chief Software Architect, Trilogy (Remote) - $...",800000.0,MEDIAN_SALARY,executive,it services and it consulting,business development
2195,Registered Nurse or Licensed Practical Nurse -...,785358.0,MEDIAN_SALARY,unknown,staffing and recruiting,health care provider
9644,"Director of Product, MyBSWHealth",750000.0,MEDIAN_SALARY,director,hospitals and health care,marketing
34029,Litigation Partner,750000.0,RANGE_MIDPOINT,director,law practice,legal
22696,Oral Surgeon - DDS/DMD,750000.0,MEDIAN_SALARY,mid-senior level,hospitals and health care,health care provider
34057,Labor & Employment Partner,750000.0,RANGE_MIDPOINT,director,law practice,legal
34092,Trust and Estates Partner,750000.0,RANGE_MIDPOINT,director,law practice,legal
34103,Intellectual Property Partner,750000.0,RANGE_MIDPOINT,director,law practice,legal
28542,Senior Sales Account Executive - Enterprise,750000.0,MEDIAN_SALARY,mid-senior level,software development,business development
9539,"Director of Product, MyBSWHealth",750000.0,MEDIAN_SALARY,director,hospitals and health care,marketing
45748,Python Developer,750000.0,RANGE_MIDPOINT,mid-senior level,capital markets,engineering
46598,Senior Software Engineer,750000.0,RANGE_MIDPOINT,mid-senior level,financial services,engineering
45693,Network Engineer,750000.0,RANGE_MIDPOINT,mid-senior level,capital markets,engineering
8747,Senior Project Manager,750000.0,MEDIAN_SALARY,mid-senior level,pharmaceutical manufacturing,information technology
40167,Oral Surgeon,700000.0,RANGE_MIDPOINT,mid-senior level,hospitals and health care,health care provider
40956,NEO4J- Senior Database administrator,700000.0,RANGE_MIDPOINT,unknown,it services and it consulting,information technology
23589,Orthopedic Surgeon,680000.0,MEDIAN_SALARY,mid-senior level,staffing and recruiting,health care provider

In [11]:
experience_salary = (
    salary_df
    .groupby(
        "formatted_experience_level",
        dropna=False
    )[
        "target_annual_salary"
    ]
    .agg(
        jobs="count",
        mean_salary="mean",
        median_salary="median",
        min_salary="min",
        max_salary="max"
    )
    .sort_values(
        "median_salary",
        ascending=False
    )
)

display(experience_salary)

,jobs,mean_salary,median_salary,min_salary,max_salary
formatted_experience_level,,,,,
executive,503,198401.071471,187500.0,40750.0,800000.0
director,1824,171222.619005,166450.0,12000.0,750000.0
mid-senior level,17285,113838.070474,107500.0,10000.0,950000.0
unknown,10945,94471.129264,78000.0,10000.0,925000.0
associate,5084,83702.341217,73000.0,16000.0,960000.0
entry level,11995,64967.411407,52250.0,10000.0,998426.0
internship,486,55090.517788,48880.0,15400.0,250000.0

In [12]:
experience_salary["median_vs_overall_pct"] = (
    (
        experience_salary["median_salary"]
        / salary_df["target_annual_salary"].median()
    ) - 1
) * 100

display(experience_salary)

,jobs,mean_salary,median_salary,min_salary,max_salary,median_vs_overall_pct
formatted_experience_level,,,,,,
executive,503,198401.071471,187500.0,40750.0,800000.0,127.272727
director,1824,171222.619005,166450.0,12000.0,750000.0,101.757576
mid-senior level,17285,113838.070474,107500.0,10000.0,950000.0,30.303030
unknown,10945,94471.129264,78000.0,10000.0,925000.0,-5.454545
associate,5084,83702.341217,73000.0,16000.0,960000.0,-11.515152
entry level,11995,64967.411407,52250.0,10000.0,998426.0,-36.666667
internship,486,55090.517788,48880.0,15400.0,250000.0,-40.751515

In [13]:
print("skill_list dtype:")
print(salary_df["skill_list"].dtype)

print("\nSample values:")

display(
    salary_df[
        ["title", "skill_list", "skill_count"]
    ]
    .head(30)
)

skill_list dtype:
object

Sample values:

,title,skill_list,skill_count
0,Hearing Care Provider,OTHER,1
1,Cook,MANAGEMENT|MANUFACTURING,2
2,Principal Cloud Security Architect (Remote),INFORMATION_TECHNOLOGY,1
3,Dishwasher,MANAGEMENT|MANUFACTURING,2
4,Insights Analyst - Auto Industry,ANALYST|INFORMATION_TECHNOLOGY|RESEARCH,3
5,Sales Manager,BUSINESS_DEVELOPMENT|SALES,2
6,Custodian/Janitor,MANAGEMENT|MANUFACTURING,2
7,Body Technician,ENGINEERING|INFORMATION_TECHNOLOGY,2
8,Controls Engineer,ENGINEERING|INFORMATION_TECHNOLOGY,2
9,CDL Class B Driver,MANAGEMENT|MANUFACTURING,2
10,"Senior Manager, Indirect Procurement",GENERAL_BUSINESS|MANAGEMENT|STRATEGY_PLANNING,3
11,CDL A Delivery Driver,MANAGEMENT|MANUFACTURING,2
12,Sales Manager,BUSINESS_DEVELOPMENT|SALES,2
13,Sales Manager,BUSINESS_DEVELOPMENT|SALES,2
14,Sales Manager,BUSINESS_DEVELOPMENT|SALES,2
15,Senior Insights Analyst - Financial Services team,ANALYST|INFORMATION_TECHNOLOGY|RESEARCH,3
16,Sales Manager,BUSINESS_DEVELOPMENT|SALES,2
17,Writer,MARKETING|PUBLIC_RELATIONS|WRITING_EDITING,3
18,Sales Manager,BUSINESS_DEVELOPMENT|SALES,2
19,Estimator In Training,MANAGEMENT|MANUFACTURING,2
20,Finisher/Carpenter,MANAGEMENT|MANUFACTURING,2
21,Sales Manager,BUSINESS_DEVELOPMENT|SALES,2
22,BCBA [5159],ADMINISTRATIVE,1
23,Sales Manager,BUSINESS_DEVELOPMENT|SALES,2
24,Sales Manager,BUSINESS_DEVELOPMENT|SALES,2
25,Sales Manager,BUSINESS_DEVELOPMENT|SALES,2
26,Staff Pharmacist,HEALTH_CARE_PROVIDER,1
27,Body Technician,ENGINEERING|INFORMATION_TECHNOLOGY,2
28,Admissions Processing Supervisor,ACCOUNTING_AUDITING|FINANCE,2
29,Sales Manager,BUSINESS_DEVELOPMENT|SALES,2

In [14]:
from collections import Counter
import numpy as np
import ast

def normalize_skill_value(value):

    if value is None:
        return []

    if isinstance(value, float) and pd.isna(value):
        return []

    if isinstance(value, np.ndarray):
        return value.tolist()

    if isinstance(value, list):
        return value

    if isinstance(value, tuple):
        return list(value)

    if isinstance(value, str):

        value = value.strip()

        if not value:
            return []

        # Try Python-list representation
        if value.startswith("[") and value.endswith("]"):
            try:
                parsed = ast.literal_eval(value)

                if isinstance(parsed, list):
                    return parsed

            except Exception:
                pass

        # Otherwise treat as delimiter-separated
        if "|" in value:
            return [
                x.strip()
                for x in value.split("|")
                if x.strip()
            ]

        return [value]

    return []

In [15]:
salary_df["skills_normalized"] = (
    salary_df["skill_list"]
    .apply(normalize_skill_value)
)

In [16]:
salary_df["actual_skill_count"] = (
    salary_df["skills_normalized"].apply(len)
)

comparison = salary_df[
    [
        "skill_count",
        "actual_skill_count"
    ]
]

display(comparison.head(30))

    skill_count  actual_skill_count
0             1                   1
1             2                   2
2             1                   1
3             2                   2
4             3                   3
5             2                   2
6             2                   2
7             2                   2
8             2                   2
9             2                   2
10            3                   3
11            2                   2
12            2                   2
13            2                   2
14            2                   2
15            3                   3
16            2                   2
17            3                   3
18            2                   2
19            2                   2
20            2                   2
21            2                   2
22            1                   1
23            2                   2
24            2                   2
25            2                   2
26            1                   1
27            2                   2
28            2                   2
29            2                   2

In [17]:
print(
    "Rows where skill_count differs:",
    (
        salary_df["skill_count"]
        != salary_df["actual_skill_count"]
    ).sum()
)

Rows where skill_count differs: 0

In [19]:
has_skills = (
    salary_df["actual_skill_count"] > 0
)

print(
    "Total jobs:",
    len(salary_df)
)

print(
    "Jobs with skills:",
    has_skills.sum()
)

print(
    "Skill coverage:",
    has_skills.mean() * 100,
    "%"
)

Total jobs: 48122
Jobs with skills: 47428
Skill coverage: 98.55783217655126 %

In [20]:
print(
    salary_df["actual_skill_count"].describe()
)

count    48122.000000
mean         1.697353
std          0.732764
min          0.000000
25%          1.000000
50%          2.000000
75%          2.000000
max          3.000000
Name: actual_skill_count, dtype: float64

In [21]:
display(
    salary_df[
        "actual_skill_count"
    ]
    .value_counts()
    .sort_index()
    .head(30)
)

actual_skill_count
0      694
1    20323
2    19958
3     7147
Name: count, dtype: int64

In [22]:
print(
    "> 5 skills:",
    (salary_df["actual_skill_count"] > 5).sum()
)

print(
    "> 10 skills:",
    (salary_df["actual_skill_count"] > 10).sum()
)

print(
    "> 20 skills:",
    (salary_df["actual_skill_count"] > 20).sum()
)

> 5 skills: 0
> 10 skills: 0
> 20 skills: 0

In [23]:
skill_counter = Counter()

for skills in salary_df["skills_normalized"]:
    skill_counter.update(
        str(skill).strip().lower()
        for skill in skills
        if str(skill).strip()
    )

skill_counts = pd.DataFrame(
    skill_counter.items(),
    columns=["skill", "job_count"]
)

skill_counts["percentage"] = (
    skill_counts["job_count"]
    / len(salary_df)
    * 100
)

skill_counts = (
    skill_counts
    .sort_values(
        "job_count",
        ascending=False
    )
    .reset_index(drop=True)
)

display(skill_counts.head(50))

                     skill  job_count  percentage
0   information_technology       9736   20.231911
1                    sales       7623   15.840987
2               management       7300   15.169777
3            manufacturing       6275   13.039774
4              engineering       5202   10.810025
5     health_care_provider       4887   10.155438
6     business_development       4734    9.837496
7                    other       4624    9.608911
8                  finance       4038    8.391172
9      accounting_auditing       3111    6.464819
10          administrative       2453    5.097461
11               marketing       2387    4.960309
12      project_management       1970    4.093762
13                 analyst       1643    3.414239
14        customer_service       1491    3.098375
15                   legal       1291    2.682765
16                research       1262    2.622501
17         human_resources       1259    2.616267
18                  design       1026    2.132081
19              consulting       1025    2.130003
20        general_business        765    1.589709
21               education        751    1.560617
22            art_creative        722    1.500353
23       quality_assurance        717    1.489963
24                training        690    1.433856
25       strategy_planning        651    1.352812
26      product_management        648    1.346577
27         writing_editing        619    1.286314
28        public_relations        583    1.211504
29            supply_chain        522    1.084743
30                 science        460    0.955904
31              production        384    0.797972
32             advertising        374    0.777191
33              purchasing        274    0.569386
34            distribution        183    0.380283

In [24]:
skill_salary = []

for skill in skill_counts["skill"]:

    mask = salary_df[
        "skills_normalized"
    ].apply(
        lambda skills: skill in [
            str(x).strip().lower()
            for x in skills
        ]
    )

    subset = salary_df.loc[
        mask,
        "target_annual_salary"
    ]

    if len(subset) >= 30:

        skill_salary.append({
            "skill": skill,
            "jobs": len(subset),
            "mean_salary": subset.mean(),
            "median_salary": subset.median()
        })

skill_salary_df = (
    pd.DataFrame(skill_salary)
    .sort_values(
        "jobs",
        ascending=False
    )
)

display(skill_salary_df.head(50))

                     skill  jobs    mean_salary  median_salary
0   information_technology  9736  117207.933152      112500.00
1                    sales  7623   94339.077733       75900.00
2               management  7300   75211.668697       59509.60
3            manufacturing  6275   68650.300297       55161.60
4              engineering  5202  127702.064441      120000.00
5     health_care_provider  4887   99008.795598       87048.00
6     business_development  4734   97559.274256       78282.28
7                    other  4624   76211.996785       58240.00
8                  finance  4038  105004.387640       92274.00
9      accounting_auditing  3111   97911.530203       87500.00
10          administrative  2453   71580.581523       60000.00
11               marketing  2387  101395.072474       85000.00
12      project_management  1970  119783.653216      114896.25
13                 analyst  1643  104028.725630       95000.00
14        customer_service  1491   63602.028870       50400.00
15                   legal  1291  137417.463164      115000.00
16                research  1262  111906.221197       93600.00
17         human_resources  1259   96798.157998       86320.00
18                  design  1026  100142.905507       91520.00
19              consulting  1025  124226.587024      115000.00
20        general_business   765   96212.462601       75000.00
21               education   751   71754.721731       64480.00
22            art_creative   722   94368.913089       80000.00
23       quality_assurance   717   95490.420544       87500.00
24                training   690   69806.847000       59500.00
25       strategy_planning   651  133242.215054      125900.00
26      product_management   648  147369.790926      142475.00
27         writing_editing   619   88439.248086       76000.00
28        public_relations   583   89717.896852       72498.40
29            supply_chain   522   97901.368716       90000.00
30                 science   460  113390.142391       90763.75
31              production   384   80149.469010       70000.00
32             advertising   374  117825.510963      105623.20
33              purchasing   274   96954.129818       92180.00
34            distribution   183   76267.598415       64043.20

In [25]:
skills_to_check = [
    "python",
    "machine learning",
    "artificial intelligence",
    "deep learning",
    "tensorflow",
    "pytorch",
    "aws",
    "azure",
    "docker",
    "kubernetes",
    "sql",
    "excel",
    "sales",
    "marketing",
]

In [26]:
display(
    skill_salary_df[
        skill_salary_df["skill"].isin(
            skills_to_check
        )
    ]
    .sort_values(
        "median_salary",
        ascending=False
    )
)

        skill  jobs    mean_salary  median_salary
11  marketing  2387  101395.072474        85000.0
1       sales  7623   94339.077733        75900.0

In [27]:
industry_salary = (
    salary_df
    .groupby(
        "top_industry",
        dropna=False
    )[
        "target_annual_salary"
    ]
    .agg(
        jobs="count",
        mean_salary="mean",
        median_salary="median"
    )
    .sort_values(
        "jobs",
        ascending=False
    )
)

display(industry_salary.head(30))

,jobs,mean_salary,median_salary
top_industry,,,
hospitals and health care,4944,94829.725653,82126.00
staffing and recruiting,3972,95796.890252,85000.00
it services and it consulting,2750,115563.547556,111500.00
financial services,2224,117398.740796,106150.00
retail,2055,52595.817200,40560.00
software development,1571,134186.154395,130500.00
banking,1315,104304.386350,92500.00
accounting,1126,98788.064423,90000.00
construction,1096,97296.438686,92500.00
biotechnology research,937,122549.415027,110000.00
government administration,875,85410.486446,75833.00
manufacturing,860,86333.719186,78447.60
advertising services,826,103207.195702,85000.00
hospitality,765,63382.627111,50232.00
insurance,736,96361.286236,87500.00
higher education,726,70748.499683,61552.50
real estate,707,84380.484109,67500.00
business consulting and services,678,113998.086615,100440.00
law practice,667,135127.484783,105000.00
non-profit organizations,660,72581.141833,62500.00
food and beverage services,639,68331.537277,58150.00
"appliances, electrical, and electronics manufacturing",557,96363.209919,85280.00
telecommunications,548,87872.716460,69850.00
food and beverage manufacturing,531,71460.912608,57500.00
"technology, information and internet",478,136605.574268,130499.25
medical equipment manufacturing,450,104031.649300,98020.25
information services,428,149660.957710,146926.00
"transportation, logistics, supply chain and storage",399,65364.276404,52104.00
industrial machinery manufacturing,382,82854.407906,72800.00
motor vehicle manufacturing,369,81192.019160,72500.00

In [28]:
display(
    industry_salary[
        industry_salary["jobs"] >= 100
    ]
    .sort_values(
        "median_salary",
        ascending=False
    )
    .head(30)
)

,jobs,mean_salary,median_salary
top_industry,,,
information services,428,149660.957710,146926.00
semiconductor manufacturing,131,132399.992405,137550.00
computer hardware manufacturing,268,137062.812313,137000.00
computer and network security,266,143558.464023,135000.00
software development,1571,134186.154395,130500.00
"technology, information and internet",478,136605.574268,130499.25
defense and space manufacturing,365,129150.318493,126800.00
computers and electronics manufacturing,102,132678.239216,119800.00
"technology, information and media",156,120577.587179,115000.00
it services and it consulting,2750,115563.547556,111500.00
biotechnology research,937,122549.415027,110000.00
building construction,103,106632.957282,107500.00
financial services,2224,117398.740796,106150.00
law practice,667,135127.484783,105000.00
engineering services,112,106648.501786,102500.00
airlines and aviation,201,104824.903682,102500.00
oil and gas,202,109714.123342,100787.00
business consulting and services,678,113998.086615,100440.00
civil engineering,346,102598.287543,100134.00
public safety,125,97802.561600,100000.00
architecture and planning,212,106909.280189,100000.00
medical equipment manufacturing,450,104031.649300,98020.25
research services,104,104643.375000,97886.00
legal services,232,118310.432500,97000.00
utilities,302,98840.396424,96854.75
aviation and aerospace component manufacturing,297,104345.132997,96000.00
entertainment providers,358,113823.125545,94300.00
pharmaceutical manufacturing,352,110715.964659,93828.80
construction,1096,97296.438686,92500.00
banking,1315,104304.386350,92500.00

In [29]:
display(
    industry_salary[
        industry_salary["jobs"] >= 100
    ]
    .sort_values(
        "median_salary",
        ascending=False
    )
    .head(30)
)

,jobs,mean_salary,median_salary
top_industry,,,
information services,428,149660.957710,146926.00
semiconductor manufacturing,131,132399.992405,137550.00
computer hardware manufacturing,268,137062.812313,137000.00
computer and network security,266,143558.464023,135000.00
software development,1571,134186.154395,130500.00
"technology, information and internet",478,136605.574268,130499.25
defense and space manufacturing,365,129150.318493,126800.00
computers and electronics manufacturing,102,132678.239216,119800.00
"technology, information and media",156,120577.587179,115000.00
it services and it consulting,2750,115563.547556,111500.00
biotechnology research,937,122549.415027,110000.00
building construction,103,106632.957282,107500.00
financial services,2224,117398.740796,106150.00
law practice,667,135127.484783,105000.00
engineering services,112,106648.501786,102500.00
airlines and aviation,201,104824.903682,102500.00
oil and gas,202,109714.123342,100787.00
business consulting and services,678,113998.086615,100440.00
civil engineering,346,102598.287543,100134.00
public safety,125,97802.561600,100000.00
architecture and planning,212,106909.280189,100000.00
medical equipment manufacturing,450,104031.649300,98020.25
research services,104,104643.375000,97886.00
legal services,232,118310.432500,97000.00
utilities,302,98840.396424,96854.75
aviation and aerospace component manufacturing,297,104345.132997,96000.00
entertainment providers,358,113823.125545,94300.00
pharmaceutical manufacturing,352,110715.964659,93828.80
construction,1096,97296.438686,92500.00
banking,1315,104304.386350,92500.00

In [30]:
state_salary = (
    salary_df
    .groupby(
        "company_state",
        dropna=False
    )[
        "target_annual_salary"
    ]
    .agg(
        jobs="count",
        mean_salary="mean",
        median_salary="median"
    )
    .sort_values(
        "jobs",
        ascending=False
    )
)

display(state_salary.head(30))

                jobs    mean_salary  median_salary
company_state
ca              4649  111421.653865    100000.0000
california      4267  114930.315884    100500.0000
ny              3355  103400.509080     91520.0000
0               3251  108772.927901     93288.0000
texas           2018   86881.877966     76825.0000
new york        1537  105273.868048     91520.0000
illinois        1332   88168.093983     72500.0000
georgia         1052   88498.432381     79040.0000
tx               982   85413.082800     70000.0000
il               958   77879.076033     67487.1525
va               943  106044.907253    105270.5000
florida          933   93835.242508     75000.0000
wa               892  118090.443268    114062.0000
new jersey       848  101141.209452     92500.0000
ma               828   98235.553611     90000.0000
nj               807   93186.710688     79375.0000
fl               789   89985.661781     75000.0000
pa               738   77383.342459     63071.2500
virginia         717   94377.421192     86500.0000
ga               654   89973.975130     85000.0000
ohio             643   72802.204160     60000.0000
oh               609   60747.802053     49025.6000
north carolina   582   80634.950515     65510.0000
washington       556  106097.946340     90176.4825
tennessee        549   74724.039226     62254.4000
england          548  115843.930109    105000.0000
massachusetts    540   90871.308472     82500.0000
co               536   90232.160159     80000.0000
colorado         531   96984.778588     86902.4000
pennsylvania     529   71123.464754     60000.0000

In [31]:
company_size_salary = (
    salary_df
    .groupby(
        "company_size",
        dropna=False
    )[
        "target_annual_salary"
    ]
    .agg(
        jobs="count",
        mean_salary="mean",
        median_salary="median"
    )
)

display(company_size_salary)

               jobs    mean_salary  median_salary
company_size
1.0            4215  100533.275153        87500.0
2.0            5988  101453.114192        90000.0
3.0            4054  102844.659124        90000.0
4.0            3748   96443.390830        83658.0
5.0            9093   96743.387170        83200.0
6.0            4027   88734.522689        75000.0
7.0           14615   91575.304723        74880.0
unknown        2382  109294.058673        90000.0

In [32]:
company_size_salary = (
    salary_df
    .groupby(
        "company_size",
        dropna=False
    )[
        "target_annual_salary"
    ]
    .agg(
        jobs="count",
        mean_salary="mean",
        median_salary="median"
    )
)

display(company_size_salary)

               jobs    mean_salary  median_salary
company_size
1.0            4215  100533.275153        87500.0
2.0            5988  101453.114192        90000.0
3.0            4054  102844.659124        90000.0
4.0            3748   96443.390830        83658.0
5.0            9093   96743.387170        83200.0
6.0            4027   88734.522689        75000.0
7.0           14615   91575.304723        74880.0
unknown        2382  109294.058673        90000.0

In [33]:
print(
    "Unique titles:",
    salary_df["title"].nunique()
)

print(
    "Total jobs:",
    len(salary_df)
)

Unique titles: 31415
Total jobs: 48122

In [34]:
title_salary = (
    salary_df
    .groupby("title")
    ["target_annual_salary"]
    .agg(
        jobs="count",
        mean_salary="mean",
        median_salary="median"
    )
    .sort_values(
        "jobs",
        ascending=False
    )
)

display(
    title_salary.head(30)
)

,jobs,mean_salary,median_salary
title,,,
Senior Accountant,186,90298.116667,90000.0000
Administrative Assistant,159,52561.913836,47320.0000
Project Manager,153,110131.401209,110000.0000
Staff Accountant,150,67859.150500,67500.0000
Customer Service Representative,130,41883.783077,40300.0000
Controller,129,138675.174419,135000.0000
Executive Assistant,124,84386.629032,80000.0000
Retail Sales Associate,112,41980.650000,49500.0000
Account Executive,108,85116.832917,75000.0000
Sales Manager,108,172317.037037,175000.0000
Accounting Manager,96,104036.469323,103776.5275
Accountant,86,73127.030233,67600.0000
Software Engineer,83,149542.753012,132500.0000
General Manager,79,90053.386899,77500.0000
Assistant Manager,75,41868.530667,39520.0000
Account Manager,75,81222.110667,73750.0000
Package Handler - Part Time (Warehouse like),70,37096.057143,36140.0000
Senior Software Engineer,68,170275.580882,151670.0000
Operations Manager,66,88567.088788,82500.0000
Registered Nurse,65,97340.494154,94640.0000
Financial Analyst,65,86018.492308,82500.0000
Maintenance Technician,61,57256.681967,56690.4000
Sales Associate,59,38898.454237,35880.0000
Accounts Payable Specialist,58,54828.244397,54080.0000
Electrical Engineer,57,110176.317544,103500.0000
Sales Director [Owner/Operator],57,201182.000000,201182.0000
Sales Representative,55,77229.178182,60000.0000
Inside Sales Representative,54,63558.533333,56617.6000
Outside Sales Representative,53,89400.943396,80000.0000
Data Analyst,52,96798.155769,90000.0000

In [35]:
display(
    title_salary[
        title_salary["jobs"] >= 20
    ]
    .sort_values(
        "median_salary",
        ascending=False
    )
    .head(30)
)

                                 jobs    mean_salary  median_salary
title
Chief Financial Officer            25  231700.000000      220000.00
Sales Director [Owner/Operator]    57  201182.000000      201182.00
Senior Data Scientist              20  175925.000000      181500.00
Sales Manager                     108  172317.037037      175000.00
Senior Product Manager             20  164691.050000      160850.00
Senior Software Engineer           68  170275.580882      151670.00
Full Stack Engineer                24  137560.416667      149500.00
Financial Controller               33  137921.969697      145000.00
Sales Director                     20  139734.849500      141250.00
Senior Project Manager             46  153402.600000      140200.00
Associate Veterinarian             21  155476.190476      140000.00
Tax Manager                        49  131172.244898      137500.00
Senior Data Engineer               21  142096.071429      135000.00
Controller                        129  138675.174419      135000.00
Software Engineer                  83  149542.753012      132500.00
Data Engineer                      28  132494.696429      130520.00
Construction Manager               23  134155.565217      130500.00
Nurse Practitioner                 28  126907.892857      128375.00
Attorney                           24  140221.158333      126250.00
Finance Manager                    28  125271.714286      126000.00
Associate Attorney                 44  125641.352273      125953.25
Program Manager                    46  123084.582609      123860.00
Data Scientist                     29  136535.858621      122500.00
Human Resources Director           20  123128.950000      122500.00
Senior Electrical Engineer         23  127610.869565      122500.00
Assistant Controller               39  123654.712179      120500.00
Construction Project Manager       47  117696.595745      120000.00
Product Manager                    36  125293.500000      118550.00
Network Engineer                   36  133956.805556      118015.00
Construction Superintendent        41  118780.487805      117500.00

In [36]:
print("=" * 80)
print("FEATURE SIGNAL SUMMARY")
print("=" * 80)

print(
    "\nTarget standard deviation:",
    salary_df["target_annual_salary"].std()
)

print(
    "Target median:",
    salary_df["target_annual_salary"].median()
)

print(
    "\nExperience groups:",
    salary_df["formatted_experience_level"]
    .nunique(dropna=True)
)

print(
    "Industry groups:",
    salary_df["top_industry"]
    .nunique(dropna=True)
)

print(
    "State groups:",
    salary_df["company_state"]
    .nunique(dropna=True)
)

print(
    "Country groups:",
    salary_df["company_country"]
    .nunique(dropna=True)
)

print(
    "Unique titles:",
    salary_df["title"]
    .nunique()
)

print(
    "Unique skills:",
    len(skill_counts)
)

================================================================================
FEATURE SIGNAL SUMMARY
================================================================================

Target standard deviation: 60434.54297821553
Target median: 82500.0

Experience groups: 7
Industry groups: 348
State groups: 382
Country groups: 50
Unique titles: 31415
Unique skills: 35